### PR TITLE
Add linux-4.9 support

### PR DESCRIPTION
**Pull request by vel21ripn**

### CODE REVIEW

**Comment by micron10** [comment]
OKi i try and installa new patch but after machine boot and add iptables rull : 

iptables -t mangle -A POSTROUTING -o eth0+ -j IMQ --todev 0
iptables -t mangle -A POSTROUTING -o eth1+ -j IMQ --todev 1

mashine stop access. i go and login in monitor and keyboard and remove iptables and machine start access from outside.
i try to down and up imq but not change only when stop traffik to move from imq machine start access.

**Comment by k0ste** [comment]
Yes, this fixed in #57

**Comment by micron10** [comment]
Hi
Yes first is fix after machine boot with iptables rulls have access and work.
next problem if have iptables rulls and imq is up machine work and not have problem.
but after down imq0 machine stop access .
i go to keyboard and up imq direct from console and machine start access.

**Comment by k0ste** [comment]
This patch does not include patch "allow traffic to go even after imq device is down" presented in this repo in #44 (original here https://github.com/gfreewind/linuximq-HighPerf/pull/1). Perhaps @bbonev can be moved it to 4.9.

**Comment by micron10** [comment]
Hi yes k0ste i check this and in new kernel and new imq this patch not apply not found may be need to update and add to imq main patch

**Pull request merged**
