### PR TITLE
Enhance the performance of IMQ

### PR DESCRIPTION
**Pull request by gfreewind**
Enhance the performance of IMQ
    1. Merge the changes(new module param imq_dev_accurate_stats) to 3.18 and 4.1;
    2. Remove the frozen/stop check of IMQ device when xmit skb;
    3. Remove the skb_cb_store_lock;

### CODE REVIEW

**Comment by coolex** [comment]
Hi Feng,
today I test patches on kernels:
3.14.41 - OK
3.18.16 - OK
4.0.5 - OK
4.1.0 - OK

All test was: 
- routed 2 interfaces (eth0 and eth1)
- 2 IMQ devices
iptables -t mangle -A PREROUTING -i eth1 -j IMQ --todev 0
iptables -t mangle -A POSTROUTING -o eth1 -j IMQ --todev 1
- IPv4 a IPv6 traffic shaping with multiple HTB classes
- IPv4 MASQUERADE on output (eth0)
- iptables firewall
- ipset address lists
maybey today night I will testing it on real traffic (about 1000 home users) :-D

**Comment by gfreewind** [comment]
Good news:)

Do you use the latest patch and how about the performance?

**Comment by gfreewind** [comment]
I just add one module param, you could try to it to avoid one lock. It should enhance the performance again.

**Comment by coolex** [comment]
I hope so, I download latest from here https://github.com/imq/linuximq/tree/master/latest

Testing in LAB looks good, but real traffic is much different. I must move testing on real users than maybe today.

**Pull request merged**
