### PR TITLE
Add Linux 4.8.8 support.

### PR DESCRIPTION
**Pull request by k0ste**

### CODE REVIEW

**Comment by micron10** [comment]
Hi Konstantin
Make image with new patch and work but after many of hour machine stop
respons and need hard reboot from power

m.






*IPacct ltd. Micron*

**Comment by mysticall** [comment]
ERROR: "err_unlock" used but not defined - linux-4.8.5

sed -i 's/goto err_unlock;/goto err;/' linux-4.8.8-imq.diff

**Comment by micron10** [comment]
Ready change and start test








*IPacct ltd. Micron*

**Comment by micron10** [comment]
OKi i test machine work 3 day and 19 hour and stop access and traffic
transit
after down imq traffic run fine without any error and crash








*IPacct ltd. Micron*

**Pull request merged**
